name: "Reusable setup"
description: "Install Node and dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: "npm"

    - name: Install package dependencies
      shell: bash
      run: npm ci --workspaces

    - name: Build package
      shell: bash
      run: npm run build --workspace=packages/generator

    - name: Generate Prisma client and IDB client
      shell: bash
      run: cd packages/usage && npm ci && npx prisma generate
