name: 'Node and Dependency install'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Build package
      shell: bash
      run: npm ci --workspace=packages/generator && npm run build --workspace=packages/generator

    - name: Install Node Dependencies
      shell: bash
      run: npm ci --workspace=packages/usage
