name: Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check **/*.{ts,js,md}
  
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/action
      - name: Run lint 
        run: npx eslint '**/*.{js,ts}'

  
