name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/

      - name: Publish
        working-directory: ./packages/generator
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run
